pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["installation_and_updates.htm","Installation and Updates","Installation and Updates Top Previous Next IQTools Lite uses ClickOnce deployment technology to allow for easy installation and automatic updating...",""],
["introduction.htm","Introduction","Introduction Top Next IQTools is a robust data analysis and reporting application developed by Futures Group. Deployed in over 200 sites spanning ...",""],
["iqc_sitedetails.htm","IQC_SiteDetails","IQC_SiteDetails Top Previous Next This view contains site specific identifiers usually entered as part of EMR configuration. # Name Type Descripti...",""],
["query_guide.htm","Query Guide","Query Guide Top Previous Next IQTools hides the complexity of EMR databases by creating easy to use tables and views that combine multiple databas...",""],
["tmp_ancmothers.htm","tmp_ANCMothers","tmp_ANCMothers Top Previous Next All pregnant women receiving PMTCT services are listed in this table. This includes women already registered in t...",""],
["tmp_artpatients.htm","tmp_ARTPatients","tmp_ARTPatients Top Previous Next All ART Patients are located in this table providing useful information such as start ART Dates, regimens and mo...",""],
["tmp_clinicalencounters.htm","tmp_ClinicalEncounters","tmp_ClinicalEncounters Top Previous Next Patient data collected at routine follow ups such as vitals, opportunistic infections, WHO and WAB stagin...",""],
["tmp_familyinfo.htm","tmp_FamilyInfo","tmp_FamilyInfo Top Previous Family information for patients is routinely collected. Initially at enrollment and continuously at follow ups and hom...",""],
["tmp_hei.htm","tmp_HEI","tmp_HEI Top Previous Next All HIV Exposed infants are listed in this profile table. In IQCare these are infants below two years registered in the ...",""],
["tmp_labs.htm","tmp_Labs","tmp_Labs Top Previous Next IQTools exposes lab data in a friendly format with enrollment, baseline and 6 month interval classification for easy qu...",""],
["tmp_laststatus.htm","tmp_LastStatus","tmp_LastStatus Top Previous Next This table contains a list of all patient with a corresponding drop out reason and date. tmp_lastStatus applies C...",""],
["tmp_ois.htm","tmp_OIs","tmp_OIs Top Previous Next All reported opportunistic infections are extracted from tmp_ClinicalEncounters and stored in this table for easy queryi...",""],
["tmp_patientmaster.htm","tmp_PatientMaster","tmp_PatientMaster Top Previous Next Patient bio data usually collected at registration and initial evaluation is located in the patient master tab...",""],
["tmp_pharmacy.htm","tmp_Pharmacy","tmp_Pharmacy Top Previous Next All drugs dispensed to patients are extracted into this table. ART regimens are reformatted in alphabetical order o...",""],
["tmp_pregnancies.htm","tmp_Pregnancies","tmp_Pregnancies Top Previous Next This table lists all unique pregnancies recorded in the EMR. A combination of pregnancy flags, LMP and EDD dates...",""],
["tmp_tbpatients.htm","tmp_TBPatients","tmp_TBPatients Top Previous Next All patients diagnosed with TB, both HIV+ and -, are extracted into this profile table. In IQCare, these are pati...",""]];
